nelmio_api_doc:
    documentation:
        info:
            title: Cart API
            description: Basic management of an online shoppping Cart
            version: 1.0.0
        definitions:
            ExistingCart:
                description: "Body for Carts already existing, either when we query them (GET) or when we wanna update them (PUT)."
                type: object
                properties:
                    id:
                        type: string
                        example: "2FBF3B2C-7D90-4CF6-80AE-CF924C046C0F"
                        description: "Uuid for an existing Cart"
                    cartProducts:
                        type: array
                        items:
                            $ref: "#/definitions/CartProduct"
            NewCart:
                description: "Body for a Cart to be created. As such doesn't contain any id and may or may not include CartProducts."
                type: object
                properties:
                    cartProducts:
                        type: array
                        items:
                            $ref: "#/definitions/CartProduct"
            CartProduct:
                description: "Information for a Product in a Cart. To test it make sure the productId exists in the DB."
                type: object
                properties:
                    quantity:
                        type: integer
                        example: 3
                        description: "How many of the Product is to be added to the Cart"
                    productId:
                        type: string
                        example:  "2FBF3B2C-7D90-4CF6-80AE-CF924C046C0F"
                        description: "The id for an existing Product in uuid format."
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
